### ISSUE TITLE
Where are the pretrained weights?

### ISSUE THREAD

**Issue by yahskapar** [facebookresearch/projectaria_eyetracking#1]
Hi there, I'm someone who's trying to use the code in this repo to get some gaze data from recordings produced using Project Aria eyeglasses. When I try running the demo, I get the following error:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/aria_eye/bin/eyetracking_demo", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/aria_eye/lib/python3.8/site-packages/projectaria_eyetracking/model_inference_demo.py", line 78, in main
    inference_model = infer.EyeGazeInference(
  File "/home/user/anaconda3/envs/aria_eye/lib/python3.8/site-packages/projectaria_eyetracking/inference/infer.py", line 47, in __init__
    self.load_config()
  File "/home/user/anaconda3/envs/aria_eye/lib/python3.8/site-packages/projectaria_eyetracking/inference/infer.py", line 51, in load_config
    with open(self.model_config_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/envs/aria_eye/lib/python3.8/site-packages/projectaria_eyetracking/inference/model/pretrained_weights/social_eyes_uncertainty_v1/config.yaml'
```
Which indicates I'm missing a required `.yaml` file and likely additional files related to the pretrained model. Where can I get these missing items? I can't seem to find anything about this in the [Project Aria Docs](https://facebookresearch.github.io/projectaria_tools/).

**Comment by yahskapar** [comment]
Never mind - whoops, just realized they're provided in the repo itself within `projectaria_eyetracking/model/pretrained_weights`. I had to manually point to the right files using the parameters in `model_inference_demo.py`.
